---
- hosts: web
  become: true
  vars:
    zbx_srv_ip: 158.160.27.172
    zbx_agent_hostname: "{{ ansible_hostname if ansible_hostname  else zabbix_agent_hostname }}"
  tasks:
    - name: Check OS
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }}-{{ ansible_distribution }}{{ ansible_distribution_version }}-{{ ansible_distribution_release }}"

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Download and install zabbix repo
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.0/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_6.0-4+{{ ansible_distribution | lower }}{{ ansible_distribution_version }}_all.deb
      when: ansible_os_family == "Debian"

    - name: Install zabbix-agent
      ansible.builtin.apt:
        pkg:
          - zabbix-agent
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Change zabbix_agentd.conf Hostname
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname=*'
        line: "Hostname={{ zbx_agent_hostname }}"
        state: present

    - name: Change zabbix_agentd.conf ServerActive
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zbx_srv_ip }}"
        state: present

    - name: Change zabbix_agentd.conf Server
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zbx_srv_ip }}"
        state: present

    - name: Restart and enable zabbix-agent
      ansible.builtin.systemd:
        name: zabbix-agent
        state: restarted
        enabled: true
